QT.qmlcompiler.VERSION = 6.11.2
QT.qmlcompiler.name = QtQmlCompiler
QT.qmlcompiler.module = QtQmlCompiler
QT.qmlcompiler.libs = $$QT_MODULE_LIB_BASE
QT.qmlcompiler.ldflags = 
QT.qmlcompiler.includes = $$QT_MODULE_LIB_BASE/QtQmlCompiler.framework/Headers
QT.qmlcompiler.frameworks = $$QT_MODULE_LIB_BASE
QT.qmlcompiler.bins = $$QT_MODULE_BIN_BASE
QT.qmlcompiler.plugin_types = qmllint
QT.qmlcompiler.depends =  core qml
QT.qmlcompiler.run_depends = qmltoolingsettings_private
QT.qmlcompiler.uses = 
QT.qmlcompiler.module_config = v2 lib_bundle
QT.qmlcompiler.DEFINES = QT_QMLCOMPILER_LIB
QT.qmlcompiler.enabled_features = 
QT.qmlcompiler.disabled_features = 
QT_CONFIG += 
QT_MODULES += qmlcompiler

