QT.qml_private.VERSION = 6.11.2
QT.qml_private.name = QtQml
QT.qml_private.module =
QT.qml_private.libs = $$QT_MODULE_LIB_BASE
QT.qml_private.includes = $$QT_MODULE_LIB_BASE/QtQml.framework/Versions/A/Headers/6.11.2 $$QT_MODULE_LIB_BASE/QtQml.framework/Versions/A/Headers/6.11.2/QtQml
QT.qml_private.frameworks = 
QT.qml_private.depends = core_private qml
QT.qml_private.uses = 
QT.qml_private.module_config = v2 lib_bundle internal_module
QT.qml_private.enabled_features = qml-profiler qml-preview qml-xml-http-request qml-locale qml-animation qml-worker-script qml-itemmodel qml-xmllistmodel qml-type-loader-thread qml-python qmlcontextpropertydump
QT.qml_private.disabled_features = qml-jit
