QT.labsfolderlistmodel_private.VERSION = 6.11.2
QT.labsfolderlistmodel_private.name = QtLabsFolderListModel
QT.labsfolderlistmodel_private.module =
QT.labsfolderlistmodel_private.libs = $$QT_MODULE_LIB_BASE
QT.labsfolderlistmodel_private.includes = $$QT_MODULE_LIB_BASE/QtLabsFolderListModel.framework/Versions/A/Headers/6.11.2 $$QT_MODULE_LIB_BASE/QtLabsFolderListModel.framework/Versions/A/Headers/6.11.2/QtLabsFolderListModel
QT.labsfolderlistmodel_private.frameworks = 
QT.labsfolderlistmodel_private.depends = labsfolderlistmodel
QT.labsfolderlistmodel_private.uses = 
QT.labsfolderlistmodel_private.module_config = v2 lib_bundle internal_module
QT.labsfolderlistmodel_private.enabled_features = 
QT.labsfolderlistmodel_private.disabled_features = 
