QT.gui.VERSION = 6.11.2
QT.gui.name = QtGui
QT.gui.module = QtGui
QT.gui.libs = $$QT_MODULE_LIB_BASE
QT.gui.ldflags = 
QT.gui.includes = $$QT_MODULE_LIB_BASE/QtGui.framework/Headers
QT.gui.frameworks = $$QT_MODULE_LIB_BASE
QT.gui.bins = $$QT_MODULE_BIN_BASE
QT.gui.plugin_types = accessiblebridge platforms platforms/darwin xcbglintegrations platformthemes platforminputcontexts generic iconengines imageformats egldeviceintegrations wayland-graphics-integration-client wayland-decoration-client wayland-shell-integration
QT.gui.depends =  core
QT.gui.run_depends = dbus
QT.gui.uses = opengl
QT.gui.module_config = v2 lib_bundle
QT.gui.CONFIG = opengl
QT.gui.DEFINES = QT_GUI_LIB
QT.gui.enabled_features = emojisegmenter freetype harfbuzz opengl metal ico sessionmanager texthtmlparser textmarkdownreader textmarkdownwriter textodfwriter cssparser draganddrop action cursor clipboard wheelevent tabletevent im highdpiscaling validator standarditemmodel filesystemmodel imageformatplugin movie imageformat_bmp imageformat_ppm imageformat_xbm imageformat_xpm imageformat_png imageformat_jpeg image_heuristic_mask image_text picture colornames pdf desktopservices systemtrayicon accessibility whatsthis undocommand undostack undogroup
QT.gui.disabled_features = accessibility-atspi-bridge fontconfig opengles2 opengles3 opengles31 opengles32 dynamicgl vulkan openvg egl xcb xcb-glx-plugin xkbcommon system-textmarkdownreader wayland waylandscanner
QT_CONFIG += emojisegmenter freetype harfbuzz opengl metal ico sessionmanager texthtmlparser textmarkdownreader textmarkdownwriter textodfwriter cssparser draganddrop action cursor clipboard wheelevent tabletevent im highdpiscaling validator standarditemmodel filesystemmodel imageformatplugin movie imageformat_bmp imageformat_ppm imageformat_xbm imageformat_xpm imageformat_png imageformat_jpeg image_heuristic_mask image_text picture colornames pdf desktopservices systemtrayicon accessibility whatsthis undocommand undostack undogroup
QT_MODULES += gui

