QT.qmlworkerscript_private.VERSION = 6.11.2
QT.qmlworkerscript_private.name = QtQmlWorkerScript
QT.qmlworkerscript_private.module =
QT.qmlworkerscript_private.libs = $$QT_MODULE_LIB_BASE
QT.qmlworkerscript_private.includes = $$QT_MODULE_LIB_BASE/QtQmlWorkerScript.framework/Versions/A/Headers/6.11.2 $$QT_MODULE_LIB_BASE/QtQmlWorkerScript.framework/Versions/A/Headers/6.11.2/QtQmlWorkerScript
QT.qmlworkerscript_private.frameworks = 
QT.qmlworkerscript_private.depends = core_private qml_private qmlworkerscript
QT.qmlworkerscript_private.uses = 
QT.qmlworkerscript_private.module_config = v2 lib_bundle internal_module
QT.qmlworkerscript_private.enabled_features = 
QT.qmlworkerscript_private.disabled_features = 
