QT.network_private.VERSION = 6.11.2
QT.network_private.name = QtNetwork
QT.network_private.module =
QT.network_private.libs = $$QT_MODULE_LIB_BASE
QT.network_private.includes = $$QT_MODULE_LIB_BASE/QtNetwork.framework/Versions/A/Headers/6.11.2 $$QT_MODULE_LIB_BASE/QtNetwork.framework/Versions/A/Headers/6.11.2/QtNetwork
QT.network_private.frameworks = 
QT.network_private.depends = core_private network
QT.network_private.uses = 
QT.network_private.module_config = v2 lib_bundle internal_module
QT.network_private.enabled_features = libresolv res_setservers system-proxies publicsuffix-qt
QT.network_private.disabled_features = libproxy linux-netlink networklistmanager publicsuffix-system
QMAKE_LIBS_GSSAPI = -framework GSS
QMAKE_LIBS_LIBRESOLV = -lresolv
