QT.qmlcompiler_private.VERSION = 6.11.2
QT.qmlcompiler_private.name = QtQmlCompiler
QT.qmlcompiler_private.module =
QT.qmlcompiler_private.libs = $$QT_MODULE_LIB_BASE
QT.qmlcompiler_private.includes = $$QT_MODULE_LIB_BASE/QtQmlCompiler.framework/Versions/A/Headers/6.11.2 $$QT_MODULE_LIB_BASE/QtQmlCompiler.framework/Versions/A/Headers/6.11.2/QtQmlCompiler
QT.qmlcompiler_private.frameworks = 
QT.qmlcompiler_private.depends = qml_private qmltoolingsettings_private qmlcompiler
QT.qmlcompiler_private.uses = 
QT.qmlcompiler_private.module_config = v2 lib_bundle internal_module
QT.qmlcompiler_private.enabled_features = 
QT.qmlcompiler_private.disabled_features = 
