QT.labssettings_private.VERSION = 6.11.2
QT.labssettings_private.name = QtLabsSettings
QT.labssettings_private.module =
QT.labssettings_private.libs = $$QT_MODULE_LIB_BASE
QT.labssettings_private.includes = $$QT_MODULE_LIB_BASE/QtLabsSettings.framework/Versions/A/Headers/6.11.2 $$QT_MODULE_LIB_BASE/QtLabsSettings.framework/Versions/A/Headers/6.11.2/QtLabsSettings
QT.labssettings_private.frameworks = 
QT.labssettings_private.depends = labssettings
QT.labssettings_private.uses = 
QT.labssettings_private.module_config = v2 lib_bundle internal_module
QT.labssettings_private.enabled_features = 
QT.labssettings_private.disabled_features = 
