QT_ARCH = arm64
QT_BUILDABI = 
QT_LIBCPP_ABI_TAG = 
QT.global.enabled_features = version_tagging shared rpath framework signaling_nan thread future concurrent dbus test_gui test_squish shared trivial_auto_var_init_pattern stack_protector libcpp_hardening shared rpath reduce_exports
QT.global.disabled_features = static cross_compile pkg-config debug_and_release separate_debug_info appstore-compliant simulator_and_device force_asserts c++20 c++2a c++2b c++2c reduce_relocations wasm-simd128 wasm-exceptions wasm-jspi zstd openssl-linked opensslv11 opensslv30
QT.global.disabled_features += release build_all
QT_CONFIG += shared no-pkg-config rpath qt_framework reduce_exports release
CONFIG += release  shared qt_framework plugin_manifest trivial_auto_var_init_pattern stack_protector libcpp_hardening
QT_VERSION = 6.11.2
QT_MAJOR_VERSION = 6
QT_MINOR_VERSION = 11
QT_PATCH_VERSION = 2

QT_APPLE_CLANG_MAJOR_VERSION = 21
QT_APPLE_CLANG_MINOR_VERSION = 0
QT_APPLE_CLANG_PATCH_VERSION = 0
QT_MAC_SDK_VERSION = 27.0
QMAKE_MACOSX_DEPLOYMENT_TARGET = 13
QT_MAC_SDK_VERSION_MIN = 14
QT_MAC_SDK_VERSION_MAX = 26
QT_ARCHS = $$QT_ARCH
