QT.qmlxmllistmodel_private.VERSION = 6.11.2
QT.qmlxmllistmodel_private.name = QtQmlXmlListModel
QT.qmlxmllistmodel_private.module =
QT.qmlxmllistmodel_private.libs = $$QT_MODULE_LIB_BASE
QT.qmlxmllistmodel_private.includes = $$QT_MODULE_LIB_BASE/QtQmlXmlListModel.framework/Versions/A/Headers/6.11.2 $$QT_MODULE_LIB_BASE/QtQmlXmlListModel.framework/Versions/A/Headers/6.11.2/QtQmlXmlListModel
QT.qmlxmllistmodel_private.frameworks = 
QT.qmlxmllistmodel_private.depends = core_private qmlxmllistmodel
QT.qmlxmllistmodel_private.uses = 
QT.qmlxmllistmodel_private.module_config = v2 lib_bundle internal_module
QT.qmlxmllistmodel_private.enabled_features = 
QT.qmlxmllistmodel_private.disabled_features = 