QT.qmlmeta_private.VERSION = 6.11.2
QT.qmlmeta_private.name = QtQmlMeta
QT.qmlmeta_private.module =
QT.qmlmeta_private.libs = $$QT_MODULE_LIB_BASE
QT.qmlmeta_private.includes = $$QT_MODULE_LIB_BASE/QtQmlMeta.framework/Versions/A/Headers/6.11.2 $$QT_MODULE_LIB_BASE/QtQmlMeta.framework/Versions/A/Headers/6.11.2/QtQmlMeta
QT.qmlmeta_private.frameworks = 
QT.qmlmeta_private.depends = qml_private qmlmodels_private qmlworkerscript_private qmlmeta
QT.qmlmeta_private.uses = 
QT.qmlmeta_private.module_config = v2 lib_bundle internal_module
QT.qmlmeta_private.enabled_features = 
QT.qmlmeta_private.disabled_features = 