# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...4.2)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS Qt6::LabsQmlModels)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target Qt6::LabsQmlModels
add_library(Qt6::LabsQmlModels SHARED IMPORTED)
set_property(TARGET Qt6::LabsQmlModels PROPERTY FRAMEWORK 1)

set_target_properties(Qt6::LabsQmlModels PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_COMPILE_DEFINITIONS "QT_LABSQMLMODELS_LIB"
  INTERFACE_INCLUDE_DIRECTORIES "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/include;/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/include/QtLabsQmlModels;/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/lib/QtLabsQmlModels.framework/Headers"
  INTERFACE_QT_MAJOR_VERSION "6"
  INTERFACE_SOURCES "\$<\$<BOOL:\$<TARGET_PROPERTY:QT_CONSUMES_METATYPES>>:/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/src/labs/models/meta_types/qt6labsqmlmodels_metatypes.json>"
  _qt_config_module_name "labsqmlmodels"
  _qt_is_internal_library "TRUE"
  _qt_is_internal_target "TRUE"
  _qt_is_public_module "TRUE"
  _qt_module_has_headers "ON"
  _qt_module_has_private_headers "TRUE"
  _qt_module_has_public_headers "TRUE"
  _qt_module_include_name "QtLabsQmlModels"
  _qt_module_interface_name "LabsQmlModels"
  _qt_module_relative_include_dir "../../../include/QtLabsQmlModels"
  _qt_package_name "Qt6LabsQmlModels"
  _qt_package_version "6.11.2"
  _qt_private_module_target_name "LabsQmlModelsPrivate"
  _qt_qml_backing_library_and_plugin_are_same_target "FALSE"
  _qt_qml_module_class_name "QtQmlLabsModelsPlugin"
  _qt_qml_module_has_plugin "TRUE"
  _qt_qml_module_installed_plugin_target "Qt6::labsmodelsplugin"
  _qt_qml_module_installed_qmldir_path "qml/Qt/labs/qmlmodels/qmldir"
  _qt_qml_module_is_backing_target "TRUE"
  _qt_qml_module_plugin_target "labsmodelsplugin"
  _qt_qml_module_target_path "Qt/labs/qmlmodels"
  _qt_qml_module_uri "Qt.labs.qmlmodels"
  _qt_qml_module_version "6.11"
  _qt_sbom_cydx_bom_serial_number_uuid "dacc209f-f1a5-5efd-9d61-1c0298aa370a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:dacc209f-f1a5-5efd-9d61-1c0298aa370a/1#SPDXRef-Package-qtdeclarative-qt-module-LabsQmlModels-b812a27e4d8e"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_MODULE"
  _qt_sbom_package_name "LabsQmlModels"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-module-LabsQmlModels-b812a27e4d8e"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.2-host-darwin-arm64-target-macos-arm64-a69b510a-8ad9-5e51-ab03-bb54c11bd620"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-b812a27e4d8e"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-b812a27e4d8e:SPDXRef-Package-qtdeclarative-qt-module-LabsQmlModels-b812a27e4d8e"
)

# Import target "Qt6::LabsQmlModels" for configuration "Release"
set_property(TARGET Qt6::LabsQmlModels APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::LabsQmlModels PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "Qt6::QmlModels;Qt6::Qml"
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/lib/QtLabsQmlModels.framework/Versions/A/QtLabsQmlModels"
  IMPORTED_SONAME_RELEASE "@rpath/QtLabsQmlModels.framework/Versions/A/QtLabsQmlModels"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
