
        # Include helpers functions.
        include("/Users/felixjaschul/CLionProjects/qutebrowser/qt6/qtbase/cmake/QtPublicCMakeIncludeGuardHelpers.cmake")
        include("/Users/felixjaschul/CLionProjects/qutebrowser/qt6/qtbase/cmake/QtPublicCMakeHelpers.cmake")
        include("/Users/felixjaschul/CLionProjects/qutebrowser/qt6/qtbase/cmake/QtPublicSbomExternalReferenceHelpers.cmake")
        include("/Users/felixjaschul/CLionProjects/qutebrowser/qt6/qtbase/cmake/QtPublicSbomOpsHelpers.cmake")

        # QT_SBOM_BUILD_TIME be set to FALSE at install time, so don't override if it's set.
        # This allows reusing the same cmake file for both build and install.
        if(NOT DEFINED QT_SBOM_BUILD_TIME)
            set(QT_SBOM_BUILD_TIME TRUE)

            # Set CMAKE_INSTALL_PREFIX for build time SBOMs to the build dir,
            # because a repo's SBOM generation might refer to it, and when it is empty,
            # it will try to write into a subdirectory of the root dir, e.g. '/sbom' dir,
            # failing due to lack of permissions.
            if(NOT DEFINED CMAKE_INSTALL_PREFIX OR NOT CMAKE_INSTALL_PREFIX)
                set(QT_SBOM_BUILD_SBOM_INSTALL_PREFIX "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase")
                set(CMAKE_INSTALL_PREFIX "${QT_SBOM_BUILD_SBOM_INSTALL_PREFIX}")
            endif()
        endif()
        if(NOT QT_SBOM_OUTPUT_PATH)
            set(QT_SBOM_OUTPUT_DIR "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/sbom")
            set(QT_SBOM_OUTPUT_PATH "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/sbom/qtbase-6.11.2.spdx")
            set(QT_SBOM_OUTPUT_PATH_WITHOUT_EXT "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/sbom/qtbase-6.11.2")
            file(MAKE_DIRECTORY "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/sbom")
        endif()
        
        set(QT_SBOM_PACKAGES "")
        set(QT_SBOM_PACKAGES_WITH_VERIFICATION_CODES "")

        include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/append_document_to_staging.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-tool-syncqt-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-tool-syncqt-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Bootstrap-Attribution-pcre2-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Bootstrap-Attribution-pcre2-sljit-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-Bootstrap-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-tool-moc-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-tool-moc-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-tool-rcc-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-tool-rcc-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-tool-tracepointgen-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-tool-tracepointgen-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-tool-tracegen-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-tool-tracegen-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-tool-cmake-automoc-parser-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-tool-cmake-automoc-parser-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-BundledPcre2-Attribution-pcre2-sljit-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-bundled-3rdparty-module-BundledPcre2-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Core-Attribution-unicode-character-database-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Core-Attribution-unicode-cldr-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Core-Attribution-tlexpected-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Core-Attribution-siphash-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Core-Attribution-blake2-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Core-Attribution-md4-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Core-Attribution-md5-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Core-Attribution-sha1-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Core-Attribution-sha3-endian-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Core-Attribution-sha3-keccak-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Core-Attribution-rfc6234-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Core-Attribution-tinycbor-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Core-Attribution-qeventdispatcher-cf-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Core-Attribution-doubleconversion-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Core-Attribution-easing-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Core-Attribution-forkfd-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Core-Attribution-tika-mimetypes-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-Core-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-module-Core-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-plugin-QDarwinCameraPermissionPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QDarwinCameraPermissionPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-plugin-QDarwinMicrophonePermissionPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QDarwinMicrophonePermissionPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-plugin-QDarwinBluetoothPermissionPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QDarwinBluetoothPermissionPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-plugin-QDarwinContactsPermissionPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QDarwinContactsPermissionPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-plugin-QDarwinCalendarPermissionPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QDarwinCalendarPermissionPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-plugin-QDarwinLocationPermissionPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QDarwinLocationPermissionPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-bundled-3rdparty-module-BundledLibpng-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-bundled-3rdparty-module-BundledLibpng-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-bundled-3rdparty-module-PngPrivate-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-bundled-3rdparty-module-BundledLibjpeg16bits-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-bundled-3rdparty-module-BundledLibjpeg12bits-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-bundled-3rdparty-module-BundledLibjpeg-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-bundled-3rdparty-module-BundledLibjpeg-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-bundled-3rdparty-module-JpegPrivate-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-BundledFreetype-Attribution-freetype-zlib-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-BundledFreetype-Attribution-freetype-bdf-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-BundledFreetype-Attribution-freetype-pcf-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-bundled-3rdparty-module-BundledFreetype-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-bundled-3rdparty-module-BundledFreetype-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-FreetypePrivate-Attribution-freetype-zlib-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-FreetypePrivate-Attribution-freetype-bdf-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-FreetypePrivate-Attribution-freetype-pcf-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-bundled-3rdparty-module-FreetypePrivate-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-bundled-3rdparty-module-BundledHarfbuzz-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-bundled-3rdparty-module-HarfbuzzPrivate-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-Concurrent-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-module-Concurrent-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-Sql-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-module-Sql-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Network-Attribution-psl-data-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Network-Attribution-libpsl-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-Network-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-module-Network-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-Xml-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-module-Xml-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-DBus-Attribution-libdbus-1-headers-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-DBus-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-module-DBus-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-tool-uic-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-tool-uic-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-tool-qdbuscpp2xml-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-tool-qdbuscpp2xml-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-tool-qdbusxml2cpp-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-tool-qdbusxml2cpp-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-tool-qlalr-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-tool-qlalr-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-tool-qvkgen-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-tool-qvkgen-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-tool-qtpaths-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-tool-qtpaths-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-tool-androiddeployqt-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-tool-androiddeployqt-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-tool-androidtestrunner-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-tool-androidtestrunner-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-tool-macdeployqt-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-tool-macdeployqt-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-tool-wasmdeployqt-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-tool-wasmdeployqt-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Gui-Attribution-rhi-miniengine-d3d12-mipmap-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Gui-Attribution-opengl-headers-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Gui-Attribution-opengl-es2-headers-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Gui-Attribution-grayraster-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Gui-Attribution-smooth-scaling-algorithm-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Gui-Attribution-xserverhelper-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Gui-Attribution-aglfn-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Gui-Attribution-vulkanmemoryallocator-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Gui-Attribution-emoji-segmenter-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Gui-Attribution-webgradients-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Gui-Attribution-icc-srgb-color-profile-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Gui-Attribution-md4c-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-Gui-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-module-Gui-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-OpenGL-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-module-OpenGL-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-Widgets-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-module-Widgets-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-OpenGLWidgets-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-module-OpenGLWidgets-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-DeviceDiscoverySupportPrivate-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-module-DeviceDiscoverySupportPrivate-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-FbSupportPrivate-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-module-FbSupportPrivate-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-TestInternalsPrivate-Attribution-cmake-runcmake-test-modules-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-TestInternalsPrivate-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Test-Attribution-catch2-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Test-Attribution-cycle-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Test-Attribution-linuxperf-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Test-Attribution-valgrind-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-Test-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-module-Test-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-PrintSupport-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-module-PrintSupport-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-QSQLiteDriverPlugin-Attribution-sqlite-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-plugin-QSQLiteDriverPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QSQLiteDriverPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-plugin-QMinimalIntegrationPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QMinimalIntegrationPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-plugin-QOffscreenIntegrationPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QOffscreenIntegrationPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-QCocoaIntegrationPlugin-Attribution-cocoa-platform-plugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-plugin-QCocoaIntegrationPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QCocoaIntegrationPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-plugin-QICOPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QICOPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-plugin-QJpegPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QJpegPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-plugin-QGifPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QGifPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-plugin-QTuioTouchPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QTuioTouchPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-plugin-QMacStylePlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QMacStylePlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-plugin-QAppleNetworkInformationPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QAppleNetworkInformationPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-plugin-QSecureTransportBackendPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QSecureTransportBackendPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-plugin-QTlsBackendCertOnlyPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QTlsBackendCertOnlyPlugin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-QtLibraryInfo-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-tool-qmake-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-PackagedFile-qt-tool-qmake-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-system-build-tool-CMake-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-system-build-tool-CMake-generator-Ninja-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-system-build-tool-Compiler-AppleClang-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-system-build-tool-Linker-AppleClang-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-GlobalConfig-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-GlobalConfigPrivate-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Platform-Attribution-extra-cmake-modules-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-3rdparty-sources-Platform-Attribution-kwin-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-Platform-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-PlatformCommonInternal-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-PlatformModuleInternal-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-PlatformPluginInternal-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-PlatformAppInternal-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-PlatformToolInternal-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-qt-module-PlatformExampleInternal-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-system-3rdparty-WrapZLIB-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-system-3rdparty-WrapBacktrace-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-system-3rdparty-WrapRt-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-system-3rdparty-WrapAtomic-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-system-3rdparty-WrapResolv-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-system-3rdparty-GSSAPI-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-system-3rdparty-WrapOpenGL-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-Package-qtbase-system-3rdparty-Cups-b9a83120e846.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-LicenseRef-BSD-3-Clause-with-PCRE2-Binary-Like-Packages-Exception-0.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-LicenseRef-ICC-License-1.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-LicenseRef-Lcs-Telegraphics-2.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-LicenseRef-Qt-Commercial-3.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/SPDXRef-LicenseRef-SHA1-Public-Domain-4.cmake")
        if(QT_SBOM_BUILD_TIME)
            message(STATUS "Finalizing SPDX SBOM generation in build dir: ${QT_SBOM_OUTPUT_PATH}")
            configure_file("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/qt_sbom/staging-qtbase.spdx.in" "${QT_SBOM_OUTPUT_PATH}")
            
        endif()
