
        # Include helpers functions.
        include("/Users/felixjaschul/CLionProjects/qutebrowser/qt6/qtbase/cmake/QtPublicCMakeIncludeGuardHelpers.cmake")
        include("/Users/felixjaschul/CLionProjects/qutebrowser/qt6/qtbase/cmake/QtPublicCMakeHelpers.cmake")
        include("/Users/felixjaschul/CLionProjects/qutebrowser/qt6/qtbase/cmake/QtPublicSbomExternalReferenceHelpers.cmake")
        include("/Users/felixjaschul/CLionProjects/qutebrowser/qt6/qtbase/cmake/QtPublicSbomOpsHelpers.cmake")

        # QT_SBOM_BUILD_TIME be set to FALSE at install time, so don't override if it's set.
        # This allows reusing the same cmake file for both build and install.
        if(NOT DEFINED QT_SBOM_BUILD_TIME)
            set(QT_SBOM_BUILD_TIME TRUE)

            # Set CMAKE_INSTALL_PREFIX for build time SBOMs to the build dir,
            # because a repo's SBOM generation might refer to it, and when it is empty,
            # it will try to write into a subdirectory of the root dir, e.g. '/sbom' dir,
            # failing due to lack of permissions.
            if(NOT DEFINED CMAKE_INSTALL_PREFIX OR NOT CMAKE_INSTALL_PREFIX)
                set(QT_SBOM_BUILD_SBOM_INSTALL_PREFIX "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase")
                set(CMAKE_INSTALL_PREFIX "${QT_SBOM_BUILD_SBOM_INSTALL_PREFIX}")
            endif()
        endif()
        if(NOT QT_SBOM_OUTPUT_PATH)
            set(QT_SBOM_OUTPUT_DIR "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/sbom")
            set(QT_SBOM_OUTPUT_PATH "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/sbom/qtdeclarative-6.11.2.spdx")
            set(QT_SBOM_OUTPUT_PATH_WITHOUT_EXT "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/sbom/qtdeclarative-6.11.2")
            file(MAKE_DIRECTORY "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/sbom")
        endif()
        
        set(QT_SBOM_PACKAGES "")
        set(QT_SBOM_PACKAGES_WITH_VERIFICATION_CODES "")

        include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/append_document_to_staging.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-module-QmlToolingSettingsPrivate-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-module-QmlToolingSettingsPrivate-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-module-QmlTypeRegistrarPrivate-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-module-QmlTypeRegistrarPrivate-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-module-QmlIntegration-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-3rdparty-sources-Qml-Attribution-masm-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-module-Qml-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-module-Qml-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-module-QmlModels-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-module-QmlModels-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-plugin-modelsplugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-plugin-modelsplugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-module-QmlCore-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-module-QmlCore-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-plugin-qtqmlcoreplugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-plugin-qtqmlcoreplugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-module-QmlNetwork-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-module-QmlNetwork-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-plugin-QmlNetworkplugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QmlNetworkplugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-module-QmlWorkerScript-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-module-QmlWorkerScript-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-plugin-workerscriptplugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-plugin-workerscriptplugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-module-QmlMeta-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-module-QmlMeta-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-plugin-qmlplugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-plugin-qmlplugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-module-QmlLocalStorage-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-module-QmlLocalStorage-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-plugin-qmllocalstorageplugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-plugin-qmllocalstorageplugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-module-QmlXmlListModel-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-module-QmlXmlListModel-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-plugin-qmlxmllistmodelplugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-plugin-qmlxmllistmodelplugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-module-LabsSynchronizer-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-module-LabsSynchronizer-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-plugin-LabsSynchronizerplugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-plugin-LabsSynchronizerplugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-module-LabsSettings-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-module-LabsSettings-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-plugin-qmlsettingsplugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-plugin-qmlsettingsplugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-module-LabsQmlModels-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-module-LabsQmlModels-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-plugin-labsmodelsplugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-plugin-labsmodelsplugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-module-LabsFolderListModel-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-module-LabsFolderListModel-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-plugin-qmlfolderlistmodelplugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-plugin-qmlfolderlistmodelplugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-module-QmlCompiler-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-module-QmlCompiler-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-module-QmlDomPrivate-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-module-QmlDomPrivate-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-module-QmltcPrivate-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-module-QmltcPrivate-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-module-QmlFormatPrivate-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-module-QmlFormatPrivate-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-tool-qmlaotstats-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-tool-qmlaotstats-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-tool-qmlcachegen-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-tool-qmlcachegen-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-module-PacketProtocolPrivate-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-module-PacketProtocolPrivate-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-plugin-QQmlNativeDebugConnectorFactoryPlugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QQmlNativeDebugConnectorFactoryPlugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-plugin-QDebugMessageServiceFactoryPlugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QDebugMessageServiceFactoryPlugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-plugin-QQmlProfilerServiceFactoryPlugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QQmlProfilerServiceFactoryPlugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-plugin-QQmlDebuggerServiceFactoryPlugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QQmlDebuggerServiceFactoryPlugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-plugin-QQmlNativeDebugServiceFactoryPlugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QQmlNativeDebugServiceFactoryPlugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-plugin-QQmlDebugServerFactoryPlugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QQmlDebugServerFactoryPlugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-plugin-QTcpServerConnectionFactoryPlugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QTcpServerConnectionFactoryPlugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-plugin-QLocalClientConnectionFactoryPlugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QLocalClientConnectionFactoryPlugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-plugin-QmlLintQdsPlugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-plugin-QmlLintQdsPlugin-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-plugin-quicktooling-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-plugin-quicktooling-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-module-QmlDebugPrivate-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-module-QmlDebugPrivate-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-tool-qmldom-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-tool-qmldom-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-tool-qmllint-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-tool-qmllint-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-tool-qmltc-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-tool-qmltc-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-tool-qmltyperegistrar-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-tool-qmltyperegistrar-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-tool-qmljsrootgen-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-tool-qmljsrootgen-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-tool-qmlformat-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-tool-qmlformat-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-tool-qmlcontextpropertydump-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-tool-qmlcontextpropertydump-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-tool-qmlimportscanner-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-tool-qmlimportscanner-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-app-qml-tool-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-app-qml-tool-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-tool-qmlprofiler-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-tool-qmlprofiler-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-qt-app-qmlpreview-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-PackagedFile-qt-app-qmlpreview-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-system-build-tool-CMake-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-system-build-tool-CMake-generator-Ninja-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-system-build-tool-Compiler-AppleClang-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-Package-qtdeclarative-system-build-tool-Linker-AppleClang-b812a27e4d8e.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/SPDXRef-LicenseRef-Qt-Commercial-0.cmake")
include("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/DocumentRef-qtbase-b9a83120e846.cmake")
        if(QT_SBOM_BUILD_TIME)
            message(STATUS "Finalizing SPDX SBOM generation in build dir: ${QT_SBOM_OUTPUT_PATH}")
            configure_file("/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/qt_sbom/staging-qtdeclarative.spdx.in" "${QT_SBOM_OUTPUT_PATH}")
            
        endif()
