QT.qmlcore_private.VERSION = 6.11.2
QT.qmlcore_private.name = QtQmlCore
QT.qmlcore_private.module =
QT.qmlcore_private.libs = $$QT_MODULE_LIB_BASE
QT.qmlcore_private.includes = $$QT_MODULE_LIB_BASE/QtQmlCore.framework/Versions/A/Headers/6.11.2 $$QT_MODULE_LIB_BASE/QtQmlCore.framework/Versions/A/Headers/6.11.2/QtQmlCore
QT.qmlcore_private.frameworks = 
QT.qmlcore_private.depends = qml_private qmlcore
QT.qmlcore_private.uses = 
QT.qmlcore_private.module_config = v2 lib_bundle internal_module
QT.qmlcore_private.enabled_features = 
QT.qmlcore_private.disabled_features = 