/****************************************************************************
** Meta object code from reading C++ file 'qcoreevent.h'
**
** Created by: The Qt Meta Object Compiler version 69 (Qt 6.11.2)
**
** WARNING! All changes made in this file will be lost!
*****************************************************************************/

#include "../../../../../../qt6/qtbase/src/corelib/kernel/qcoreevent.h"
#include <QtCore/qmetatype.h>

#include <QtCore/qtmochelpers.h>

#include <memory>


#include <QtCore/qxptype_traits.h>
#if !defined(Q_MOC_OUTPUT_REVISION)
#error "The header file 'qcoreevent.h' doesn't include <QObject>."
#elif Q_MOC_OUTPUT_REVISION != 69
#error "This file was generated using the moc from 6.11.2. It"
#error "cannot be used with the include files from this version of Qt."
#error "(The moc has changed too much.)"
#endif

#ifndef Q_CONSTINIT
#define Q_CONSTINIT
#endif

QT_WARNING_PUSH
QT_WARNING_DISABLE_DEPRECATED
QT_WARNING_DISABLE_GCC("-Wuseless-cast")
namespace {
struct qt_meta_tag_ZN6QEventE_t {};
} // unnamed namespace

template <> constexpr inline auto QEvent::qt_create_metaobjectdata<qt_meta_tag_ZN6QEventE_t>()
{
    namespace QMC = QtMocConstants;
    QtMocHelpers::StringRefStorage qt_stringData {
        "QEvent",
        "Type",
        "None",
        "Timer",
        "MouseButtonPress",
        "MouseButtonRelease",
        "MouseButtonDblClick",
        "MouseMove",
        "KeyPress",
        "KeyRelease",
        "FocusIn",
        "FocusOut",
        "FocusAboutToChange",
        "Enter",
        "Leave",
        "Paint",
        "Move",
        "Resize",
        "Create",
        "Destroy",
        "Show",
        "Hide",
        "Close",
        "Quit",
        "ParentChange",
        "ParentAboutToChange",
        "ThreadChange",
        "WindowActivate",
        "WindowDeactivate",
        "ShowToParent",
        "HideToParent",
        "Wheel",
        "WindowTitleChange",
        "WindowIconChange",
        "ApplicationWindowIconChange",
        "ApplicationFontChange",
        "ApplicationLayoutDirectionChange",
        "ApplicationPaletteChange",
        "PaletteChange",
        "Clipboard",
        "Speech",
        "MetaCall",
        "SockAct",
        "WinEventAct",
        "DeferredDelete",
        "DragEnter",
        "DragMove",
        "DragLeave",
        "Drop",
        "DragResponse",
        "ChildAdded",
        "ChildPolished",
        "ChildRemoved",
        "ShowWindowRequest",
        "PolishRequest",
        "Polish",
        "LayoutRequest",
        "UpdateRequest",
        "UpdateLater",
        "EmbeddingControl",
        "ActivateControl",
        "DeactivateControl",
        "ContextMenu",
        "InputMethod",
        "TabletMove",
        "LocaleChange",
        "LanguageChange",
        "LayoutDirectionChange",
        "Style",
        "TabletPress",
        "TabletRelease",
        "OkRequest",
        "HelpRequest",
        "IconDrag",
        "FontChange",
        "EnabledChange",
        "ActivationChange",
        "StyleChange",
        "IconTextChange",
        "ModifiedChange",
        "MouseTrackingChange",
        "WindowBlocked",
        "WindowUnblocked",
        "WindowStateChange",
        "ReadOnlyChange",
        "ToolTip",
        "WhatsThis",
        "StatusTip",
        "ActionChanged",
        "ActionAdded",
        "ActionRemoved",
        "FileOpen",
        "Shortcut",
        "ShortcutOverride",
        "WhatsThisClicked",
        "ToolBarChange",
        "ApplicationActivate",
        "ApplicationActivated",
        "ApplicationDeactivate",
        "ApplicationDeactivated",
        "QueryWhatsThis",
        "EnterWhatsThisMode",
        "LeaveWhatsThisMode",
        "ZOrderChange",
        "HoverEnter",
        "HoverLeave",
        "HoverMove",
        "AcceptDropsChange",
        "ZeroTimerEvent",
        "GraphicsSceneMouseMove",
        "GraphicsSceneMousePress",
        "GraphicsSceneMouseRelease",
        "GraphicsSceneMouseDoubleClick",
        "GraphicsSceneContextMenu",
        "GraphicsSceneHoverEnter",
        "GraphicsSceneHoverMove",
        "GraphicsSceneHoverLeave",
        "GraphicsSceneHelp",
        "GraphicsSceneDragEnter",
        "GraphicsSceneDragMove",
        "GraphicsSceneDragLeave",
        "GraphicsSceneDrop",
        "GraphicsSceneWheel",
        "GraphicsSceneLeave",
        "KeyboardLayoutChange",
        "DynamicPropertyChange",
        "TabletEnterProximity",
        "TabletLeaveProximity",
        "NonClientAreaMouseMove",
        "NonClientAreaMouseButtonPress",
        "NonClientAreaMouseButtonRelease",
        "NonClientAreaMouseButtonDblClick",
        "MacSizeChange",
        "ContentsRectChange",
        "MacGLWindowChange",
        "FutureCallOut",
        "GraphicsSceneResize",
        "GraphicsSceneMove",
        "CursorChange",
        "ToolTipChange",
        "NetworkReplyUpdated",
        "GrabMouse",
        "UngrabMouse",
        "GrabKeyboard",
        "UngrabKeyboard",
        "StateMachineSignal",
        "StateMachineWrapped",
        "TouchBegin",
        "TouchUpdate",
        "TouchEnd",
        "NativeGesture",
        "RequestSoftwareInputPanel",
        "CloseSoftwareInputPanel",
        "WinIdChange",
        "Gesture",
        "GestureOverride",
        "ScrollPrepare",
        "Scroll",
        "Expose",
        "InputMethodQuery",
        "OrientationChange",
        "TouchCancel",
        "ThemeChange",
        "SockClose",
        "PlatformPanel",
        "StyleAnimationUpdate",
        "ApplicationStateChange",
        "WindowChangeInternal",
        "ScreenChangeInternal",
        "PlatformSurface",
        "Pointer",
        "TabletTrackingChange",
        "WindowAboutToChangeInternal",
        "DevicePixelRatioChange",
        "ChildWindowAdded",
        "ChildWindowRemoved",
        "ParentWindowAboutToChange",
        "ParentWindowChange",
        "SafeAreaMarginsChange",
        "User",
        "MaxUser"
    };

    QtMocHelpers::UintData qt_methods {
    };
    QtMocHelpers::UintData qt_properties {
    };
    QtMocHelpers::UintData qt_enums {
        // enum 'Type'
        QtMocHelpers::EnumData<enum Type>(1, 1, QMC::EnumFlags{}).add({
            {    2, Type::None },
            {    3, Type::Timer },
            {    4, Type::MouseButtonPress },
            {    5, Type::MouseButtonRelease },
            {    6, Type::MouseButtonDblClick },
            {    7, Type::MouseMove },
            {    8, Type::KeyPress },
            {    9, Type::KeyRelease },
            {   10, Type::FocusIn },
            {   11, Type::FocusOut },
            {   12, Type::FocusAboutToChange },
            {   13, Type::Enter },
            {   14, Type::Leave },
            {   15, Type::Paint },
            {   16, Type::Move },
            {   17, Type::Resize },
            {   18, Type::Create },
            {   19, Type::Destroy },
            {   20, Type::Show },
            {   21, Type::Hide },
            {   22, Type::Close },
            {   23, Type::Quit },
            {   24, Type::ParentChange },
            {   25, Type::ParentAboutToChange },
            {   26, Type::ThreadChange },
            {   27, Type::WindowActivate },
            {   28, Type::WindowDeactivate },
            {   29, Type::ShowToParent },
            {   30, Type::HideToParent },
            {   31, Type::Wheel },
            {   32, Type::WindowTitleChange },
            {   33, Type::WindowIconChange },
            {   34, Type::ApplicationWindowIconChange },
            {   35, Type::ApplicationFontChange },
            {   36, Type::ApplicationLayoutDirectionChange },
            {   37, Type::ApplicationPaletteChange },
            {   38, Type::PaletteChange },
            {   39, Type::Clipboard },
            {   40, Type::Speech },
            {   41, Type::MetaCall },
            {   42, Type::SockAct },
            {   43, Type::WinEventAct },
            {   44, Type::DeferredDelete },
            {   45, Type::DragEnter },
            {   46, Type::DragMove },
            {   47, Type::DragLeave },
            {   48, Type::Drop },
            {   49, Type::DragResponse },
            {   50, Type::ChildAdded },
            {   51, Type::ChildPolished },
            {   52, Type::ChildRemoved },
            {   53, Type::ShowWindowRequest },
            {   54, Type::PolishRequest },
            {   55, Type::Polish },
            {   56, Type::LayoutRequest },
            {   57, Type::UpdateRequest },
            {   58, Type::UpdateLater },
            {   59, Type::EmbeddingControl },
            {   60, Type::ActivateControl },
            {   61, Type::DeactivateControl },
            {   62, Type::ContextMenu },
            {   63, Type::InputMethod },
            {   64, Type::TabletMove },
            {   65, Type::LocaleChange },
            {   66, Type::LanguageChange },
            {   67, Type::LayoutDirectionChange },
            {   68, Type::Style },
            {   69, Type::TabletPress },
            {   70, Type::TabletRelease },
            {   71, Type::OkRequest },
            {   72, Type::HelpRequest },
            {   73, Type::IconDrag },
            {   74, Type::FontChange },
            {   75, Type::EnabledChange },
            {   76, Type::ActivationChange },
            {   77, Type::StyleChange },
            {   78, Type::IconTextChange },
            {   79, Type::ModifiedChange },
            {   80, Type::MouseTrackingChange },
            {   81, Type::WindowBlocked },
            {   82, Type::WindowUnblocked },
            {   83, Type::WindowStateChange },
            {   84, Type::ReadOnlyChange },
            {   85, Type::ToolTip },
            {   86, Type::WhatsThis },
            {   87, Type::StatusTip },
            {   88, Type::ActionChanged },
            {   89, Type::ActionAdded },
            {   90, Type::ActionRemoved },
            {   91, Type::FileOpen },
            {   92, Type::Shortcut },
            {   93, Type::ShortcutOverride },
            {   94, Type::WhatsThisClicked },
            {   95, Type::ToolBarChange },
            {   96, Type::ApplicationActivate },
            {   97, Type::ApplicationActivated },
            {   98, Type::ApplicationDeactivate },
            {   99, Type::ApplicationDeactivated },
            {  100, Type::QueryWhatsThis },
            {  101, Type::EnterWhatsThisMode },
            {  102, Type::LeaveWhatsThisMode },
            {  103, Type::ZOrderChange },
            {  104, Type::HoverEnter },
            {  105, Type::HoverLeave },
            {  106, Type::HoverMove },
            {  107, Type::AcceptDropsChange },
            {  108, Type::ZeroTimerEvent },
            {  109, Type::GraphicsSceneMouseMove },
            {  110, Type::GraphicsSceneMousePress },
            {  111, Type::GraphicsSceneMouseRelease },
            {  112, Type::GraphicsSceneMouseDoubleClick },
            {  113, Type::GraphicsSceneContextMenu },
            {  114, Type::GraphicsSceneHoverEnter },
            {  115, Type::GraphicsSceneHoverMove },
            {  116, Type::GraphicsSceneHoverLeave },
            {  117, Type::GraphicsSceneHelp },
            {  118, Type::GraphicsSceneDragEnter },
            {  119, Type::GraphicsSceneDragMove },
            {  120, Type::GraphicsSceneDragLeave },
            {  121, Type::GraphicsSceneDrop },
            {  122, Type::GraphicsSceneWheel },
            {  123, Type::GraphicsSceneLeave },
            {  124, Type::KeyboardLayoutChange },
            {  125, Type::DynamicPropertyChange },
            {  126, Type::TabletEnterProximity },
            {  127, Type::TabletLeaveProximity },
            {  128, Type::NonClientAreaMouseMove },
            {  129, Type::NonClientAreaMouseButtonPress },
            {  130, Type::NonClientAreaMouseButtonRelease },
            {  131, Type::NonClientAreaMouseButtonDblClick },
            {  132, Type::MacSizeChange },
            {  133, Type::ContentsRectChange },
            {  134, Type::MacGLWindowChange },
            {  135, Type::FutureCallOut },
            {  136, Type::GraphicsSceneResize },
            {  137, Type::GraphicsSceneMove },
            {  138, Type::CursorChange },
            {  139, Type::ToolTipChange },
            {  140, Type::NetworkReplyUpdated },
            {  141, Type::GrabMouse },
            {  142, Type::UngrabMouse },
            {  143, Type::GrabKeyboard },
            {  144, Type::UngrabKeyboard },
            {  145, Type::StateMachineSignal },
            {  146, Type::StateMachineWrapped },
            {  147, Type::TouchBegin },
            {  148, Type::TouchUpdate },
            {  149, Type::TouchEnd },
            {  150, Type::NativeGesture },
            {  151, Type::RequestSoftwareInputPanel },
            {  152, Type::CloseSoftwareInputPanel },
            {  153, Type::WinIdChange },
            {  154, Type::Gesture },
            {  155, Type::GestureOverride },
            {  156, Type::ScrollPrepare },
            {  157, Type::Scroll },
            {  158, Type::Expose },
            {  159, Type::InputMethodQuery },
            {  160, Type::OrientationChange },
            {  161, Type::TouchCancel },
            {  162, Type::ThemeChange },
            {  163, Type::SockClose },
            {  164, Type::PlatformPanel },
            {  165, Type::StyleAnimationUpdate },
            {  166, Type::ApplicationStateChange },
            {  167, Type::WindowChangeInternal },
            {  168, Type::ScreenChangeInternal },
            {  169, Type::PlatformSurface },
            {  170, Type::Pointer },
            {  171, Type::TabletTrackingChange },
            {  172, Type::WindowAboutToChangeInternal },
            {  173, Type::DevicePixelRatioChange },
            {  174, Type::ChildWindowAdded },
            {  175, Type::ChildWindowRemoved },
            {  176, Type::ParentWindowAboutToChange },
            {  177, Type::ParentWindowChange },
            {  178, Type::SafeAreaMarginsChange },
            {  179, Type::User },
            {  180, Type::MaxUser },
        }),
    };
    return QtMocHelpers::metaObjectData<QEvent, qt_meta_tag_ZN6QEventE_t>(QMC::PropertyAccessInStaticMetaCall, qt_stringData,
            qt_methods, qt_properties, qt_enums);
}
Q_CONSTINIT const QMetaObject QEvent::staticMetaObject = { {
    nullptr,
    qt_staticMetaObjectStaticContent<qt_meta_tag_ZN6QEventE_t>.stringdata,
    qt_staticMetaObjectStaticContent<qt_meta_tag_ZN6QEventE_t>.data,
    nullptr,
    nullptr,
    qt_staticMetaObjectRelocatingContent<qt_meta_tag_ZN6QEventE_t>.metaTypes,
    nullptr
} };

QT_WARNING_POP
