// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>




$<$<BOOL:qml_register_types_Qt_labs_synchronizer>:QT_DECLARE_EXTERN_SYMBOL_VOID($<JOIN:qml_register_types_Qt_labs_synchronizer,)
QT_DECLARE_EXTERN_SYMBOL_VOID(>)>

class Qt_labs_synchronizerPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    Qt_labs_synchronizerPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

$<$<BOOL:qml_register_types_Qt_labs_synchronizer>:QT_KEEP_SYMBOL($<JOIN:qml_register_types_Qt_labs_synchronizer,)
QT_KEEP_SYMBOL(>)>
    }
};



#include "LabsSynchronizerplugin_Qt_labs_synchronizerPlugin.moc"
