// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>




QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Qt_labs_synchronizer)

class Qt_labs_synchronizerPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    Qt_labs_synchronizerPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_Qt_labs_synchronizer)
    }
};



#include "LabsSynchronizerplugin_Qt_labs_synchronizerPlugin.moc"
