QT.labssynchronizer_private.VERSION = 6.11.2
QT.labssynchronizer_private.name = QtLabsSynchronizer
QT.labssynchronizer_private.module =
QT.labssynchronizer_private.libs = $$QT_MODULE_LIB_BASE
QT.labssynchronizer_private.includes = $$QT_MODULE_LIB_BASE/QtLabsSynchronizer.framework/Versions/A/Headers/6.11.2 $$QT_MODULE_LIB_BASE/QtLabsSynchronizer.framework/Versions/A/Headers/6.11.2/QtLabsSynchronizer
QT.labssynchronizer_private.frameworks = 
QT.labssynchronizer_private.depends = qml_private labssynchronizer
QT.labssynchronizer_private.uses = 
QT.labssynchronizer_private.module_config = v2 lib_bundle internal_module
QT.labssynchronizer_private.enabled_features = 
QT.labssynchronizer_private.disabled_features = 