QT.qmlmodels_private.VERSION = 6.11.2
QT.qmlmodels_private.name = QtQmlModels
QT.qmlmodels_private.module =
QT.qmlmodels_private.libs = $$QT_MODULE_LIB_BASE
QT.qmlmodels_private.includes = $$QT_MODULE_LIB_BASE/QtQmlModels.framework/Versions/A/Headers/6.11.2 $$QT_MODULE_LIB_BASE/QtQmlModels.framework/Versions/A/Headers/6.11.2/QtQmlModels
QT.qmlmodels_private.frameworks = 
QT.qmlmodels_private.depends = core_private qml_private qmlmodels
QT.qmlmodels_private.uses = 
QT.qmlmodels_private.module_config = v2 lib_bundle internal_module
QT.qmlmodels_private.enabled_features = qml-object-model qml-list-model qml-delegate-model qml-table-model qml-tree-model qml-sfpm-model
QT.qmlmodels_private.disabled_features = 