# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...4.2)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS Qt6::QmlDebugPrivate)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target Qt6::QmlDebugPrivate
add_library(Qt6::QmlDebugPrivate STATIC IMPORTED)

set_target_properties(Qt6::QmlDebugPrivate PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_COMPILE_DEFINITIONS "QT_QMLDEBUG_LIB"
  INTERFACE_INCLUDE_DIRECTORIES "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/include;/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/include/QtQmlDebug;/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/src/qmldebug;\$<\$<BOOL:\$<TARGET_PROPERTY:Qt6::QmlDebugPrivate,_qt_module_has_private_headers>>:/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/include/QtQmlDebug/6.11.2>;\$<\$<BOOL:\$<TARGET_PROPERTY:Qt6::QmlDebugPrivate,_qt_module_has_private_headers>>:/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/include/QtQmlDebug/6.11.2/QtQmlDebug>;\$<\$<BOOL:\$<TARGET_PROPERTY:Qt6::QmlDebugPrivate,_qt_module_has_private_headers>>:>;\$<\$<BOOL:\$<TARGET_PROPERTY:Qt6::QmlDebugPrivate,_qt_module_has_private_headers>>:>"
  INTERFACE_LINK_LIBRARIES "Qt6::CorePrivate;Qt6::Network;Qt6::PacketProtocolPrivate;Qt6::QmlPrivate;\$<LINK_ONLY:Qt6::PlatformModuleInternal>"
  INTERFACE_QT_MAJOR_VERSION "6"
  INTERFACE_SOURCES "\$<\$<BOOL:\$<TARGET_PROPERTY:QT_CONSUMES_METATYPES>>:/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/src/qmldebug/meta_types/qt6qmldebugprivate_metatypes.json>"
  _qt_config_module_name "qmldebug_private"
  _qt_is_internal_library "TRUE"
  _qt_is_internal_module "TRUE"
  _qt_is_internal_target "TRUE"
  _qt_module_has_headers "ON"
  _qt_module_has_private_headers "TRUE"
  _qt_module_include_name "QtQmlDebug"
  _qt_module_interface_name "QmlDebug"
  _qt_module_relative_include_dir "../../../include/QtQmlDebug"
  _qt_package_name "Qt6QmlDebugPrivate"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "dacc209f-f1a5-5efd-9d61-1c0298aa370a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:dacc209f-f1a5-5efd-9d61-1c0298aa370a/1#SPDXRef-Package-qtdeclarative-qt-module-QmlDebugPrivate-b812a27e4d8e"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_MODULE"
  _qt_sbom_package_name "QmlDebugPrivate"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-module-QmlDebugPrivate-b812a27e4d8e"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.2-host-darwin-arm64-target-macos-arm64-a69b510a-8ad9-5e51-ab03-bb54c11bd620"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-b812a27e4d8e"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-b812a27e4d8e:SPDXRef-Package-qtdeclarative-qt-module-QmlDebugPrivate-b812a27e4d8e"
)

# Import target "Qt6::QmlDebugPrivate" for configuration "Release"
set_property(TARGET Qt6::QmlDebugPrivate APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::QmlDebugPrivate PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/lib/libQt6QmlDebug.a"
  )

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "Qt6::CorePrivate" "Qt6::Network" "Qt6::PacketProtocolPrivate" "Qt6::QmlPrivate" "Qt6::PlatformModuleInternal" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
