# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...4.2)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS Qt6::qmlaotstats Qt6::qmlcachegen Qt6::qmldom Qt6::qmllint Qt6::qmltc Qt6::qmltyperegistrar Qt6::qmljsrootgen Qt6::qmlformat Qt6::qmlcontextpropertydump Qt6::qmlimportscanner Qt6::qmlprofiler)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target Qt6::qmlaotstats
add_executable(Qt6::qmlaotstats IMPORTED)

set_target_properties(Qt6::qmlaotstats PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "dacc209f-f1a5-5efd-9d61-1c0298aa370a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:dacc209f-f1a5-5efd-9d61-1c0298aa370a/1#SPDXRef-Package-qtdeclarative-qt-tool-qmlaotstats-b812a27e4d8e"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmlaotstats"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmlaotstats-b812a27e4d8e"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.2-host-darwin-arm64-target-macos-arm64-a69b510a-8ad9-5e51-ab03-bb54c11bd620"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-b812a27e4d8e"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-b812a27e4d8e:SPDXRef-Package-qtdeclarative-qt-tool-qmlaotstats-b812a27e4d8e"
)

# Create imported target Qt6::qmlcachegen
add_executable(Qt6::qmlcachegen IMPORTED)

set_target_properties(Qt6::qmlcachegen PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "dacc209f-f1a5-5efd-9d61-1c0298aa370a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:dacc209f-f1a5-5efd-9d61-1c0298aa370a/1#SPDXRef-Package-qtdeclarative-qt-tool-qmlcachegen-b812a27e4d8e"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmlcachegen"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmlcachegen-b812a27e4d8e"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.2-host-darwin-arm64-target-macos-arm64-a69b510a-8ad9-5e51-ab03-bb54c11bd620"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-b812a27e4d8e"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-b812a27e4d8e:SPDXRef-Package-qtdeclarative-qt-tool-qmlcachegen-b812a27e4d8e"
)

# Create imported target Qt6::qmldom
add_executable(Qt6::qmldom IMPORTED)

set_target_properties(Qt6::qmldom PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "dacc209f-f1a5-5efd-9d61-1c0298aa370a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:dacc209f-f1a5-5efd-9d61-1c0298aa370a/1#SPDXRef-Package-qtdeclarative-qt-tool-qmldom-b812a27e4d8e"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmldom"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmldom-b812a27e4d8e"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.2-host-darwin-arm64-target-macos-arm64-a69b510a-8ad9-5e51-ab03-bb54c11bd620"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-b812a27e4d8e"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-b812a27e4d8e:SPDXRef-Package-qtdeclarative-qt-tool-qmldom-b812a27e4d8e"
)

# Create imported target Qt6::qmllint
add_executable(Qt6::qmllint IMPORTED)

set_target_properties(Qt6::qmllint PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "dacc209f-f1a5-5efd-9d61-1c0298aa370a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:dacc209f-f1a5-5efd-9d61-1c0298aa370a/1#SPDXRef-Package-qtdeclarative-qt-tool-qmllint-b812a27e4d8e"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmllint"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmllint-b812a27e4d8e"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.2-host-darwin-arm64-target-macos-arm64-a69b510a-8ad9-5e51-ab03-bb54c11bd620"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-b812a27e4d8e"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-b812a27e4d8e:SPDXRef-Package-qtdeclarative-qt-tool-qmllint-b812a27e4d8e"
)

# Create imported target Qt6::qmltc
add_executable(Qt6::qmltc IMPORTED)

set_target_properties(Qt6::qmltc PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "dacc209f-f1a5-5efd-9d61-1c0298aa370a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:dacc209f-f1a5-5efd-9d61-1c0298aa370a/1#SPDXRef-Package-qtdeclarative-qt-tool-qmltc-b812a27e4d8e"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmltc"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmltc-b812a27e4d8e"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.2-host-darwin-arm64-target-macos-arm64-a69b510a-8ad9-5e51-ab03-bb54c11bd620"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-b812a27e4d8e"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-b812a27e4d8e:SPDXRef-Package-qtdeclarative-qt-tool-qmltc-b812a27e4d8e"
)

# Create imported target Qt6::qmltyperegistrar
add_executable(Qt6::qmltyperegistrar IMPORTED)

set_target_properties(Qt6::qmltyperegistrar PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "dacc209f-f1a5-5efd-9d61-1c0298aa370a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:dacc209f-f1a5-5efd-9d61-1c0298aa370a/1#SPDXRef-Package-qtdeclarative-qt-tool-qmltyperegistrar-b812a27e4d8e"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmltyperegistrar"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmltyperegistrar-b812a27e4d8e"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.2-host-darwin-arm64-target-macos-arm64-a69b510a-8ad9-5e51-ab03-bb54c11bd620"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-b812a27e4d8e"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-b812a27e4d8e:SPDXRef-Package-qtdeclarative-qt-tool-qmltyperegistrar-b812a27e4d8e"
)

# Create imported target Qt6::qmljsrootgen
add_executable(Qt6::qmljsrootgen IMPORTED)

set_target_properties(Qt6::qmljsrootgen PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "dacc209f-f1a5-5efd-9d61-1c0298aa370a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:dacc209f-f1a5-5efd-9d61-1c0298aa370a/1#SPDXRef-Package-qtdeclarative-qt-tool-qmljsrootgen-b812a27e4d8e"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmljsrootgen"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmljsrootgen-b812a27e4d8e"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.2-host-darwin-arm64-target-macos-arm64-a69b510a-8ad9-5e51-ab03-bb54c11bd620"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-b812a27e4d8e"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-b812a27e4d8e:SPDXRef-Package-qtdeclarative-qt-tool-qmljsrootgen-b812a27e4d8e"
)

# Create imported target Qt6::qmlformat
add_executable(Qt6::qmlformat IMPORTED)

set_target_properties(Qt6::qmlformat PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "dacc209f-f1a5-5efd-9d61-1c0298aa370a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:dacc209f-f1a5-5efd-9d61-1c0298aa370a/1#SPDXRef-Package-qtdeclarative-qt-tool-qmlformat-b812a27e4d8e"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmlformat"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmlformat-b812a27e4d8e"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.2-host-darwin-arm64-target-macos-arm64-a69b510a-8ad9-5e51-ab03-bb54c11bd620"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-b812a27e4d8e"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-b812a27e4d8e:SPDXRef-Package-qtdeclarative-qt-tool-qmlformat-b812a27e4d8e"
)

# Create imported target Qt6::qmlcontextpropertydump
add_executable(Qt6::qmlcontextpropertydump IMPORTED)

set_target_properties(Qt6::qmlcontextpropertydump PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "dacc209f-f1a5-5efd-9d61-1c0298aa370a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:dacc209f-f1a5-5efd-9d61-1c0298aa370a/1#SPDXRef-Package-qtdeclarative-qt-tool-qmlcontextpropertydump-b812a27e4d8e"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmlcontextpropertydump"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmlcontextpropertydump-b812a27e4d8e"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.2-host-darwin-arm64-target-macos-arm64-a69b510a-8ad9-5e51-ab03-bb54c11bd620"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-b812a27e4d8e"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-b812a27e4d8e:SPDXRef-Package-qtdeclarative-qt-tool-qmlcontextpropertydump-b812a27e4d8e"
)

# Create imported target Qt6::qmlimportscanner
add_executable(Qt6::qmlimportscanner IMPORTED)

set_target_properties(Qt6::qmlimportscanner PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "dacc209f-f1a5-5efd-9d61-1c0298aa370a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:dacc209f-f1a5-5efd-9d61-1c0298aa370a/1#SPDXRef-Package-qtdeclarative-qt-tool-qmlimportscanner-b812a27e4d8e"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmlimportscanner"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmlimportscanner-b812a27e4d8e"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.2-host-darwin-arm64-target-macos-arm64-a69b510a-8ad9-5e51-ab03-bb54c11bd620"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-b812a27e4d8e"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-b812a27e4d8e:SPDXRef-Package-qtdeclarative-qt-tool-qmlimportscanner-b812a27e4d8e"
)

# Create imported target Qt6::qmlprofiler
add_executable(Qt6::qmlprofiler IMPORTED)

set_target_properties(Qt6::qmlprofiler PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "dacc209f-f1a5-5efd-9d61-1c0298aa370a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:dacc209f-f1a5-5efd-9d61-1c0298aa370a/1#SPDXRef-Package-qtdeclarative-qt-tool-qmlprofiler-b812a27e4d8e"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmlprofiler"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-tool-qmlprofiler-b812a27e4d8e"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.2-host-darwin-arm64-target-macos-arm64-a69b510a-8ad9-5e51-ab03-bb54c11bd620"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-b812a27e4d8e"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-b812a27e4d8e:SPDXRef-Package-qtdeclarative-qt-tool-qmlprofiler-b812a27e4d8e"
)

# Import target "Qt6::qmlaotstats" for configuration "Release"
set_property(TARGET Qt6::qmlaotstats APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::qmlaotstats PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/libexec/qmlaotstats"
  )

# Import target "Qt6::qmlcachegen" for configuration "Release"
set_property(TARGET Qt6::qmlcachegen APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::qmlcachegen PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/libexec/qmlcachegen"
  )

# Import target "Qt6::qmldom" for configuration "Release"
set_property(TARGET Qt6::qmldom APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::qmldom PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/bin/qmldom"
  )

# Import target "Qt6::qmllint" for configuration "Release"
set_property(TARGET Qt6::qmllint APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::qmllint PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/bin/qmllint"
  )

# Import target "Qt6::qmltc" for configuration "Release"
set_property(TARGET Qt6::qmltc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::qmltc PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/bin/qmltc"
  )

# Import target "Qt6::qmltyperegistrar" for configuration "Release"
set_property(TARGET Qt6::qmltyperegistrar APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::qmltyperegistrar PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/libexec/qmltyperegistrar"
  )

# Import target "Qt6::qmljsrootgen" for configuration "Release"
set_property(TARGET Qt6::qmljsrootgen APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::qmljsrootgen PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/libexec/qmljsrootgen"
  )

# Import target "Qt6::qmlformat" for configuration "Release"
set_property(TARGET Qt6::qmlformat APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::qmlformat PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/bin/qmlformat"
  )

# Import target "Qt6::qmlcontextpropertydump" for configuration "Release"
set_property(TARGET Qt6::qmlcontextpropertydump APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::qmlcontextpropertydump PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/bin/qmlcontextpropertydump"
  )

# Import target "Qt6::qmlimportscanner" for configuration "Release"
set_property(TARGET Qt6::qmlimportscanner APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::qmlimportscanner PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/libexec/qmlimportscanner"
  )

# Import target "Qt6::qmlprofiler" for configuration "Release"
set_property(TARGET Qt6::qmlprofiler APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::qmlprofiler PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/bin/qmlprofiler"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
