QT.labsqmlmodels_private.VERSION = 6.11.2
QT.labsqmlmodels_private.name = QtLabsQmlModels
QT.labsqmlmodels_private.module =
QT.labsqmlmodels_private.libs = $$QT_MODULE_LIB_BASE
QT.labsqmlmodels_private.includes = $$QT_MODULE_LIB_BASE/QtLabsQmlModels.framework/Versions/A/Headers/6.11.2 $$QT_MODULE_LIB_BASE/QtLabsQmlModels.framework/Versions/A/Headers/6.11.2/QtLabsQmlModels
QT.labsqmlmodels_private.frameworks = 
QT.labsqmlmodels_private.depends = labsqmlmodels
QT.labsqmlmodels_private.uses = 
QT.labsqmlmodels_private.module_config = v2 lib_bundle internal_module
QT.labsqmlmodels_private.enabled_features = 
QT.labsqmlmodels_private.disabled_features = 