# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...4.2)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS Qt6::syncqt Qt6::moc Qt6::rcc Qt6::tracepointgen Qt6::tracegen Qt6::cmake_automoc_parser Qt6::qlalr Qt6::qtpaths Qt6::androiddeployqt Qt6::androidtestrunner Qt6::macdeployqt Qt6::wasmdeployqt Qt6::qmake)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target Qt6::syncqt
add_executable(Qt6::syncqt IMPORTED)

set_target_properties(Qt6::syncqt PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "980f43d9-37aa-5207-b674-9d335cb79e9a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:980f43d9-37aa-5207-b674-9d335cb79e9a/1#SPDXRef-Package-qtbase-qt-tool-syncqt-b9a83120e846"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtbase-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "syncqt"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtbase-qt-tool-syncqt-b9a83120e846"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtbase-6.11.2-host-darwin-arm64-target-macos-arm64-7f55961c-7c32-57a9-9b1e-25706f3d9a2c"
  _qt_sbom_spdx_repo_project_name_lowercase "qtbase"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtbase-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtbase-b9a83120e846"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtbase-b9a83120e846:SPDXRef-Package-qtbase-qt-tool-syncqt-b9a83120e846"
)

# Create imported target Qt6::moc
add_executable(Qt6::moc IMPORTED)

set_target_properties(Qt6::moc PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "980f43d9-37aa-5207-b674-9d335cb79e9a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:980f43d9-37aa-5207-b674-9d335cb79e9a/1#SPDXRef-Package-qtbase-qt-tool-moc-b9a83120e846"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtbase-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "moc"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtbase-qt-tool-moc-b9a83120e846"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtbase-6.11.2-host-darwin-arm64-target-macos-arm64-7f55961c-7c32-57a9-9b1e-25706f3d9a2c"
  _qt_sbom_spdx_repo_project_name_lowercase "qtbase"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtbase-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtbase-b9a83120e846"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtbase-b9a83120e846:SPDXRef-Package-qtbase-qt-tool-moc-b9a83120e846"
)

# Create imported target Qt6::rcc
add_executable(Qt6::rcc IMPORTED)

set_target_properties(Qt6::rcc PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "980f43d9-37aa-5207-b674-9d335cb79e9a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:980f43d9-37aa-5207-b674-9d335cb79e9a/1#SPDXRef-Package-qtbase-qt-tool-rcc-b9a83120e846"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtbase-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "rcc"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtbase-qt-tool-rcc-b9a83120e846"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtbase-6.11.2-host-darwin-arm64-target-macos-arm64-7f55961c-7c32-57a9-9b1e-25706f3d9a2c"
  _qt_sbom_spdx_repo_project_name_lowercase "qtbase"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtbase-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtbase-b9a83120e846"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtbase-b9a83120e846:SPDXRef-Package-qtbase-qt-tool-rcc-b9a83120e846"
)

# Create imported target Qt6::tracepointgen
add_executable(Qt6::tracepointgen IMPORTED)

set_target_properties(Qt6::tracepointgen PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "980f43d9-37aa-5207-b674-9d335cb79e9a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:980f43d9-37aa-5207-b674-9d335cb79e9a/1#SPDXRef-Package-qtbase-qt-tool-tracepointgen-b9a83120e846"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtbase-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "tracepointgen"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtbase-qt-tool-tracepointgen-b9a83120e846"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtbase-6.11.2-host-darwin-arm64-target-macos-arm64-7f55961c-7c32-57a9-9b1e-25706f3d9a2c"
  _qt_sbom_spdx_repo_project_name_lowercase "qtbase"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtbase-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtbase-b9a83120e846"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtbase-b9a83120e846:SPDXRef-Package-qtbase-qt-tool-tracepointgen-b9a83120e846"
)

# Create imported target Qt6::tracegen
add_executable(Qt6::tracegen IMPORTED)

set_target_properties(Qt6::tracegen PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "980f43d9-37aa-5207-b674-9d335cb79e9a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:980f43d9-37aa-5207-b674-9d335cb79e9a/1#SPDXRef-Package-qtbase-qt-tool-tracegen-b9a83120e846"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtbase-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "tracegen"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtbase-qt-tool-tracegen-b9a83120e846"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtbase-6.11.2-host-darwin-arm64-target-macos-arm64-7f55961c-7c32-57a9-9b1e-25706f3d9a2c"
  _qt_sbom_spdx_repo_project_name_lowercase "qtbase"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtbase-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtbase-b9a83120e846"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtbase-b9a83120e846:SPDXRef-Package-qtbase-qt-tool-tracegen-b9a83120e846"
)

# Create imported target Qt6::cmake_automoc_parser
add_executable(Qt6::cmake_automoc_parser IMPORTED)

set_target_properties(Qt6::cmake_automoc_parser PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "980f43d9-37aa-5207-b674-9d335cb79e9a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:980f43d9-37aa-5207-b674-9d335cb79e9a/1#SPDXRef-Package-qtbase-qt-tool-cmake-automoc-parser-b9a83120e846"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtbase-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "cmake_automoc_parser"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtbase-qt-tool-cmake-automoc-parser-b9a83120e846"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtbase-6.11.2-host-darwin-arm64-target-macos-arm64-7f55961c-7c32-57a9-9b1e-25706f3d9a2c"
  _qt_sbom_spdx_repo_project_name_lowercase "qtbase"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtbase-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtbase-b9a83120e846"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtbase-b9a83120e846:SPDXRef-Package-qtbase-qt-tool-cmake-automoc-parser-b9a83120e846"
)

# Create imported target Qt6::qlalr
add_executable(Qt6::qlalr IMPORTED)

set_target_properties(Qt6::qlalr PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "980f43d9-37aa-5207-b674-9d335cb79e9a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:980f43d9-37aa-5207-b674-9d335cb79e9a/1#SPDXRef-Package-qtbase-qt-tool-qlalr-b9a83120e846"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtbase-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qlalr"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtbase-qt-tool-qlalr-b9a83120e846"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtbase-6.11.2-host-darwin-arm64-target-macos-arm64-7f55961c-7c32-57a9-9b1e-25706f3d9a2c"
  _qt_sbom_spdx_repo_project_name_lowercase "qtbase"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtbase-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtbase-b9a83120e846"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtbase-b9a83120e846:SPDXRef-Package-qtbase-qt-tool-qlalr-b9a83120e846"
)

# Create imported target Qt6::qtpaths
add_executable(Qt6::qtpaths IMPORTED)

set_target_properties(Qt6::qtpaths PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "980f43d9-37aa-5207-b674-9d335cb79e9a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:980f43d9-37aa-5207-b674-9d335cb79e9a/1#SPDXRef-Package-qtbase-qt-tool-qtpaths-b9a83120e846"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtbase-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qtpaths"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtbase-qt-tool-qtpaths-b9a83120e846"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtbase-6.11.2-host-darwin-arm64-target-macos-arm64-7f55961c-7c32-57a9-9b1e-25706f3d9a2c"
  _qt_sbom_spdx_repo_project_name_lowercase "qtbase"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtbase-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtbase-b9a83120e846"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtbase-b9a83120e846:SPDXRef-Package-qtbase-qt-tool-qtpaths-b9a83120e846"
)

# Create imported target Qt6::androiddeployqt
add_executable(Qt6::androiddeployqt IMPORTED)

set_target_properties(Qt6::androiddeployqt PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "980f43d9-37aa-5207-b674-9d335cb79e9a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:980f43d9-37aa-5207-b674-9d335cb79e9a/1#SPDXRef-Package-qtbase-qt-tool-androiddeployqt-b9a83120e846"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtbase-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "androiddeployqt"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtbase-qt-tool-androiddeployqt-b9a83120e846"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtbase-6.11.2-host-darwin-arm64-target-macos-arm64-7f55961c-7c32-57a9-9b1e-25706f3d9a2c"
  _qt_sbom_spdx_repo_project_name_lowercase "qtbase"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtbase-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtbase-b9a83120e846"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtbase-b9a83120e846:SPDXRef-Package-qtbase-qt-tool-androiddeployqt-b9a83120e846"
)

# Create imported target Qt6::androidtestrunner
add_executable(Qt6::androidtestrunner IMPORTED)

set_target_properties(Qt6::androidtestrunner PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "980f43d9-37aa-5207-b674-9d335cb79e9a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:980f43d9-37aa-5207-b674-9d335cb79e9a/1#SPDXRef-Package-qtbase-qt-tool-androidtestrunner-b9a83120e846"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtbase-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "androidtestrunner"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtbase-qt-tool-androidtestrunner-b9a83120e846"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtbase-6.11.2-host-darwin-arm64-target-macos-arm64-7f55961c-7c32-57a9-9b1e-25706f3d9a2c"
  _qt_sbom_spdx_repo_project_name_lowercase "qtbase"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtbase-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtbase-b9a83120e846"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtbase-b9a83120e846:SPDXRef-Package-qtbase-qt-tool-androidtestrunner-b9a83120e846"
)

# Create imported target Qt6::macdeployqt
add_executable(Qt6::macdeployqt IMPORTED)

set_target_properties(Qt6::macdeployqt PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "980f43d9-37aa-5207-b674-9d335cb79e9a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:980f43d9-37aa-5207-b674-9d335cb79e9a/1#SPDXRef-Package-qtbase-qt-tool-macdeployqt-b9a83120e846"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtbase-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "macdeployqt"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtbase-qt-tool-macdeployqt-b9a83120e846"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtbase-6.11.2-host-darwin-arm64-target-macos-arm64-7f55961c-7c32-57a9-9b1e-25706f3d9a2c"
  _qt_sbom_spdx_repo_project_name_lowercase "qtbase"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtbase-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtbase-b9a83120e846"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtbase-b9a83120e846:SPDXRef-Package-qtbase-qt-tool-macdeployqt-b9a83120e846"
)

# Create imported target Qt6::wasmdeployqt
add_executable(Qt6::wasmdeployqt IMPORTED)

set_target_properties(Qt6::wasmdeployqt PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "980f43d9-37aa-5207-b674-9d335cb79e9a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:980f43d9-37aa-5207-b674-9d335cb79e9a/1#SPDXRef-Package-qtbase-qt-tool-wasmdeployqt-b9a83120e846"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtbase-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "wasmdeployqt"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtbase-qt-tool-wasmdeployqt-b9a83120e846"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtbase-6.11.2-host-darwin-arm64-target-macos-arm64-7f55961c-7c32-57a9-9b1e-25706f3d9a2c"
  _qt_sbom_spdx_repo_project_name_lowercase "qtbase"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtbase-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtbase-b9a83120e846"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtbase-b9a83120e846:SPDXRef-Package-qtbase-qt-tool-wasmdeployqt-b9a83120e846"
)

# Create imported target Qt6::qmake
add_executable(Qt6::qmake IMPORTED)

set_target_properties(Qt6::qmake PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_is_internal_target "TRUE"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "980f43d9-37aa-5207-b674-9d335cb79e9a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:980f43d9-37aa-5207-b674-9d335cb79e9a/1#SPDXRef-Package-qtbase-qt-tool-qmake-b9a83120e846"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtbase-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_TOOL"
  _qt_sbom_package_name "qmake"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtbase-qt-tool-qmake-b9a83120e846"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtbase-6.11.2-host-darwin-arm64-target-macos-arm64-7f55961c-7c32-57a9-9b1e-25706f3d9a2c"
  _qt_sbom_spdx_repo_project_name_lowercase "qtbase"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtbase-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtbase-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtbase-b9a83120e846"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtbase-b9a83120e846:SPDXRef-Package-qtbase-qt-tool-qmake-b9a83120e846"
)

# Import target "Qt6::syncqt" for configuration "Release"
set_property(TARGET Qt6::syncqt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::syncqt PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/libexec/syncqt"
  )

# Import target "Qt6::moc" for configuration "Release"
set_property(TARGET Qt6::moc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::moc PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/libexec/moc"
  )

# Import target "Qt6::rcc" for configuration "Release"
set_property(TARGET Qt6::rcc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::rcc PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/libexec/rcc"
  )

# Import target "Qt6::tracepointgen" for configuration "Release"
set_property(TARGET Qt6::tracepointgen APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::tracepointgen PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/libexec/tracepointgen"
  )

# Import target "Qt6::tracegen" for configuration "Release"
set_property(TARGET Qt6::tracegen APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::tracegen PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/libexec/tracegen"
  )

# Import target "Qt6::cmake_automoc_parser" for configuration "Release"
set_property(TARGET Qt6::cmake_automoc_parser APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::cmake_automoc_parser PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/libexec/cmake_automoc_parser"
  )

# Import target "Qt6::qlalr" for configuration "Release"
set_property(TARGET Qt6::qlalr APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::qlalr PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/libexec/qlalr"
  )

# Import target "Qt6::qtpaths" for configuration "Release"
set_property(TARGET Qt6::qtpaths APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::qtpaths PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/bin/qtpaths"
  )

# Import target "Qt6::androiddeployqt" for configuration "Release"
set_property(TARGET Qt6::androiddeployqt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::androiddeployqt PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/bin/androiddeployqt"
  )

# Import target "Qt6::androidtestrunner" for configuration "Release"
set_property(TARGET Qt6::androidtestrunner APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::androidtestrunner PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/bin/androidtestrunner"
  )

# Import target "Qt6::macdeployqt" for configuration "Release"
set_property(TARGET Qt6::macdeployqt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::macdeployqt PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/bin/macdeployqt"
  )

# Import target "Qt6::wasmdeployqt" for configuration "Release"
set_property(TARGET Qt6::wasmdeployqt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::wasmdeployqt PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/bin/wasmdeployqt"
  )

# Import target "Qt6::qmake" for configuration "Release"
set_property(TARGET Qt6::qmake APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::qmake PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/bin/qmake"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
