// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>




QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_QtQml_WorkerScript)

class QtQmlWorkerScriptPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtQmlWorkerScriptPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_QtQml_WorkerScript)
    }
};



#include "workerscriptplugin_QtQmlWorkerScriptPlugin.moc"
