// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>




$<$<BOOL:qml_register_types_QtQuick_LocalStorage>:QT_DECLARE_EXTERN_SYMBOL_VOID($<JOIN:qml_register_types_QtQuick_LocalStorage,)
QT_DECLARE_EXTERN_SYMBOL_VOID(>)>

class QQmlLocalStoragePlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QQmlLocalStoragePlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

$<$<BOOL:qml_register_types_QtQuick_LocalStorage>:QT_KEEP_SYMBOL($<JOIN:qml_register_types_QtQuick_LocalStorage,)
QT_KEEP_SYMBOL(>)>
    }
};



#include "qmllocalstorageplugin_QQmlLocalStoragePlugin.moc"
