QT.qmllocalstorage_private.VERSION = 6.11.2
QT.qmllocalstorage_private.name = QtQmlLocalStorage
QT.qmllocalstorage_private.module =
QT.qmllocalstorage_private.libs = $$QT_MODULE_LIB_BASE
QT.qmllocalstorage_private.includes = $$QT_MODULE_LIB_BASE/QtQmlLocalStorage.framework/Versions/A/Headers/6.11.2 $$QT_MODULE_LIB_BASE/QtQmlLocalStorage.framework/Versions/A/Headers/6.11.2/QtQmlLocalStorage
QT.qmllocalstorage_private.frameworks = 
QT.qmllocalstorage_private.depends = qmllocalstorage
QT.qmllocalstorage_private.uses = 
QT.qmllocalstorage_private.module_config = v2 lib_bundle internal_module
QT.qmllocalstorage_private.enabled_features = 
QT.qmllocalstorage_private.disabled_features = 