// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>




$<$<BOOL:qml_register_types_QtQuick_tooling>:QT_DECLARE_EXTERN_SYMBOL_VOID($<JOIN:qml_register_types_QtQuick_tooling,)
QT_DECLARE_EXTERN_SYMBOL_VOID(>)>

class QtQuick_toolingPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtQuick_toolingPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

$<$<BOOL:qml_register_types_QtQuick_tooling>:QT_KEEP_SYMBOL($<JOIN:qml_register_types_QtQuick_tooling,)
QT_KEEP_SYMBOL(>)>
    }
};



#include "quicktooling_QtQuick_toolingPlugin.moc"
