# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...4.2)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS Qt6::QmlTypeRegistrarPrivate Qt6::QmlTypeRegistrarPrivate_resources_1)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target Qt6::QmlTypeRegistrarPrivate
add_library(Qt6::QmlTypeRegistrarPrivate STATIC IMPORTED)

set_target_properties(Qt6::QmlTypeRegistrarPrivate PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_COMPILE_DEFINITIONS "QT_QMLTYPEREGISTRAR_LIB"
  INTERFACE_INCLUDE_DIRECTORIES "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/include;/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/include/QtQmlTypeRegistrar;/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/src/qmltyperegistrar;\$<\$<BOOL:\$<TARGET_PROPERTY:Qt6::QmlTypeRegistrarPrivate,_qt_module_has_private_headers>>:/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/include/QtQmlTypeRegistrar/6.11.2>;\$<\$<BOOL:\$<TARGET_PROPERTY:Qt6::QmlTypeRegistrarPrivate,_qt_module_has_private_headers>>:/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/include/QtQmlTypeRegistrar/6.11.2/QtQmlTypeRegistrar>;\$<\$<BOOL:\$<TARGET_PROPERTY:Qt6::QmlTypeRegistrarPrivate,_qt_module_has_private_headers>>:>;\$<\$<BOOL:\$<TARGET_PROPERTY:Qt6::QmlTypeRegistrarPrivate,_qt_module_has_private_headers>>:>"
  INTERFACE_LINK_LIBRARIES "Qt6::CorePrivate;\$<LINK_ONLY:Qt6::PlatformModuleInternal>;\$<\$<AND:\$<NOT:\$<STREQUAL:\$<TARGET_PROPERTY:TYPE>,STATIC_LIBRARY>>,\$<NOT:\$<BOOL:\$<TARGET_PROPERTY:Qt6::Platform,_qt_link_order_matters>>>,\$<NOT:\$<BOOL:\$<TARGET_PROPERTY:_qt_object_libraries_finalizer_mode>>>,\$<BOOL:TRUE>>:\$<TARGET_OBJECTS:Qt6::QmlTypeRegistrarPrivate_resources_1>>;Qt6::QmlTypeRegistrarPrivate_resources_1"
  INTERFACE_LINK_OPTIONS "\$<\$<AND:\$<NOT:\$<STREQUAL:\$<TARGET_PROPERTY:TYPE>,STATIC_LIBRARY>>,\$<BOOL:\$<TARGET_PROPERTY:Qt6::Platform,_qt_link_order_matters>>,\$<BOOL:\$<GENEX_EVAL:\$<TARGET_PROPERTY:Qt6::Platform,_qt_cmp0099_policy_check>>>,\$<BOOL:TRUE>>:\$<TARGET_OBJECTS:Qt6::QmlTypeRegistrarPrivate_resources_1>>"
  INTERFACE_QT_MAJOR_VERSION "6"
  INTERFACE_SOURCES "\$<\$<BOOL:\$<TARGET_PROPERTY:QT_CONSUMES_METATYPES>>:/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/src/qmltyperegistrar/meta_types/qt6qmltyperegistrarprivate_metatypes.json>;\$<\$<AND:\$<NOT:\$<STREQUAL:\$<TARGET_PROPERTY:TYPE>,STATIC_LIBRARY>>,\$<BOOL:\$<TARGET_PROPERTY:Qt6::Platform,_qt_link_order_matters>>,\$<NOT:\$<BOOL:\$<GENEX_EVAL:\$<TARGET_PROPERTY:Qt6::Platform,_qt_cmp0099_policy_check>>>>,\$<NOT:\$<BOOL:\$<TARGET_PROPERTY:_qt_object_libraries_finalizer_mode>>>,\$<BOOL:TRUE>>:\$<TARGET_OBJECTS:Qt6::QmlTypeRegistrarPrivate_resources_1>>"
  _qt_config_module_name "qmltyperegistrar_private"
  _qt_is_internal_library "TRUE"
  _qt_is_internal_module "TRUE"
  _qt_is_internal_target "TRUE"
  _qt_module_has_headers "ON"
  _qt_module_has_private_headers "TRUE"
  _qt_module_include_name "QtQmlTypeRegistrar"
  _qt_module_interface_name "QmlTypeRegistrar"
  _qt_module_relative_include_dir "../../../include/QtQmlTypeRegistrar"
  _qt_package_name "Qt6QmlTypeRegistrarPrivate"
  _qt_package_version "6.11.2"
  _qt_sbom_cydx_bom_serial_number_uuid "dacc209f-f1a5-5efd-9d61-1c0298aa370a"
  _qt_sbom_cydx_external_bom_link "urn:cdx:dacc209f-f1a5-5efd-9d61-1c0298aa370a/1#SPDXRef-Package-qtdeclarative-qt-module-QmlTypeRegistrarPrivate-b812a27e4d8e"
  _qt_sbom_cydx_external_urn_bom_version "1"
  _qt_sbom_cydx_v1_6_document_json_relative_path "sbom/qtdeclarative-6.11.2.cdx.json"
  _qt_sbom_entity_type "QT_MODULE"
  _qt_sbom_package_name "QmlTypeRegistrarPrivate"
  _qt_sbom_package_version "6.11.2"
  _qt_sbom_spdx_id "SPDXRef-Package-qtdeclarative-qt-module-QmlTypeRegistrarPrivate-b812a27e4d8e"
  _qt_sbom_spdx_relative_installed_repo_document_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_repo_document_namespace "https://qt.io/spdxdocs/qtdeclarative-6.11.2-host-darwin-arm64-target-macos-arm64-a69b510a-8ad9-5e51-ab03-bb54c11bd620"
  _qt_sbom_spdx_repo_project_name_lowercase "qtdeclarative"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtdeclarative-6.11.2.spdx.json"
  _qt_sbom_spdx_v2_document_tag_value_relative_path "sbom/qtdeclarative-6.11.2.spdx"
  _qt_sbom_spdx_v2_external_document_ref "DocumentRef-qtdeclarative-b812a27e4d8e"
  _qt_sbom_spdx_v2_external_spdx_id "DocumentRef-qtdeclarative-b812a27e4d8e:SPDXRef-Package-qtdeclarative-qt-module-QmlTypeRegistrarPrivate-b812a27e4d8e"
)

# Create imported target Qt6::QmlTypeRegistrarPrivate_resources_1
add_library(Qt6::QmlTypeRegistrarPrivate_resources_1 OBJECT IMPORTED)

set_target_properties(Qt6::QmlTypeRegistrarPrivate_resources_1 PROPERTIES
  INTERFACE_LINK_LIBRARIES "Qt6::Core;\$<LINK_ONLY:Qt6::Platform>;\$<LINK_ONLY:Qt6::PlatformModuleInternal>"
  _is_qt_propagated_object_library "TRUE"
)

# Import target "Qt6::QmlTypeRegistrarPrivate" for configuration "Release"
set_property(TARGET Qt6::QmlTypeRegistrarPrivate APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::QmlTypeRegistrarPrivate PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtbase/lib/libQt6QmlTypeRegistrar.a"
  )

# Import target "Qt6::QmlTypeRegistrarPrivate_resources_1" for configuration "Release"
set_property(TARGET Qt6::QmlTypeRegistrarPrivate_resources_1 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::QmlTypeRegistrarPrivate_resources_1 PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_RELEASE ""
  IMPORTED_OBJECTS_RELEASE "/Users/felixjaschul/CLionProjects/qutebrowser/qt-build/qtdeclarative/src/qmltyperegistrar/CMakeFiles/QmlTypeRegistrarPrivate_resources_1.dir/./.qt/rcc/qrc_jsRootMetaTypes_init.cpp.o"
  )

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "Qt6::Platform" "Qt6::CorePrivate" "Qt6::PlatformModuleInternal" "Qt6::Core" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
